version: '3'

services:

  crm-nats-server:
    container_name: crm-nats-server
    image: nats:latest
    ports:
      - "8222:8222"
      - "4222:4222"

  auth-database:
    image: postgres:13.5
    container_name: auth-database
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5431:5432'

    volumes:
      - ./auth-ms/postgres:/var/lib/postgresql/data

  clients-database:
    image: postgres:13.5
    container_name: clients-database
    environment:
      POSTGRES_DB: clients
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'

    volumes:
      - ./clients-ms/postgres:/var/lib/postgresql/data

  products-database:
    image: postgres:13.5
    container_name: products-database
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5430:5432'

    volumes:
      - ./products-ms/postgres:/var/lib/postgresql/data